import { LegalLayout, LegalSection } from "@/components/LegalLayout";

export default function TermsPage() {
  return (
    <LegalLayout title="Terms & Conditions" updated="17 July 2026">
      <LegalSection heading="Acceptance of terms">
        <p>
          By creating an account or using SignalDesk, you agree to these terms. If you do not
          agree, please do not use the service.
        </p>
      </LegalSection>
      <LegalSection heading="Service description">
        <p>
          SignalDesk provides algorithmically generated trading signals (long-term and intraday)
          across select Indian stocks, forex pairs, and cryptocurrencies, accompanied by
          AI-generated commentary. Signals are generated by rules-based technical analysis and
          are provided "as is," without guarantee of accuracy or profitability.
        </p>
      </LegalSection>
      <LegalSection heading="Subscriptions">
        <p>
          Paid subscriptions (Monthly, Quarterly, Yearly) grant full access to all covered
          instruments for the stated duration, processed via Razorpay. NIFTY 50 and XAUUSD
          signals remain free for all registered users. New users receive a 10-day trial with
          full access from the date of signup.
        </p>
      </LegalSection>
      <LegalSection heading="No investment advice">
        <p>
          Nothing on SignalDesk constitutes investment, legal, or tax advice. You are solely
          responsible for your trading decisions. See our{" "}
          <a href="/disclaimer" className="text-signal underline">
            disclaimer
          </a>{" "}
          for further detail.
        </p>
      </LegalSection>
      <LegalSection heading="Account termination">
        <p>
          We may suspend or terminate accounts that violate these terms, abuse the service, or
          engage in fraudulent payment activity.
        </p>
      </LegalSection>
      <LegalSection heading="Changes to these terms">
        <p>
          We may update these terms from time to time. Continued use of the service after
          changes constitutes acceptance of the revised terms.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
