import { LegalLayout, LegalSection } from "@/components/LegalLayout";

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Disclaimer" updated="17 July 2026">
      <LegalSection heading="Not investment advice">
        <p>
          SignalDesk is not a SEBI-registered investment advisor, research analyst, or
          stockbroker. Content on this platform — including BUY/SELL signals, entry/stop-loss/
          target levels, trend direction, confidence scores, and AI-generated commentary — is
          provided purely for informational and educational purposes and does not constitute
          investment advice, a recommendation, or a solicitation to buy or sell any financial
          instrument.
        </p>
      </LegalSection>
      <LegalSection heading="Trading risk">
        <p>
          Trading in equities, forex, and cryptocurrencies carries substantial risk of loss and
          is not suitable for every investor. Past performance of any signal or strategy is not
          indicative of future results. You should independently evaluate every trade and consult
          a SEBI-registered financial advisor before making investment decisions.
        </p>
      </LegalSection>
      <LegalSection heading="No guarantee of accuracy">
        <p>
          Signals are generated by an automated, rules-based technical engine reading market data
          from third-party providers (Twelve Data, CoinGecko, Angel One SmartAPI). Market data
          may be delayed, incomplete, or inaccurate, and the AI-generated analysis is descriptive
          commentary on the engine's output, not independent verification.
        </p>
      </LegalSection>
      <LegalSection heading="Your responsibility">
        <p>
          Any trading decision made using information from SignalDesk is made at your own
          discretion and risk. SignalDesk and its operators accept no liability for any financial
          loss arising from the use of this platform.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
